/*
 Generated by typeshare 1.13.2
*/

export type NanoId = string;

export enum Level {
  AlwaysOnTop = "alwaysontop",
  Normal = "normal",
  AlwaysOnBottom = "alwaysonbottom",
}

export interface CreateWidgetRequest {
  url: string;
  html: string;
  title: string;
  level: Level;
  transparent: boolean;
}

export interface FileConfiguration {
  html: string;
}

export interface ScrapedData {
  widget_id: string;
  value: string;
  error?: string;
  timestamp: string;
}

export interface UrlConfiguration {
  url: string;
}

export type WidgetType =
  | { type: "file"; content: FileConfiguration }
  | { type: "url"; content: UrlConfiguration };

export interface WidgetConfiguration {
  widget_id: NanoId;
  title: string;
  widget_type: WidgetType;
  level: Level;
  transparent: boolean;
}

export type Modifier =
  | {
      type: "scrape";
      content: {
        modifier_id: NanoId;
        selector: string;
      };
    }
  | {
      type: "refresh";
      content: {
        modifier_id: NanoId;
        interval_sec: number;
      };
    };

export interface WidgetModifier {
  widget_id: NanoId;
  modifier_type: Modifier;
}
