/*
 Generated by typeshare 1.13.2
*/

export type NanoId = string;

export enum Level {
	AlwaysOnTop = "alwaysontop",
	Normal = "normal",
	AlwaysOnBottom = "alwaysonbottom",
}

export interface CreateWidgetRequest {
	url: string;
	title: string;
	level: Level;
}

export interface FileConfiguration {
	html: string;
}

export interface UrlConfiguration {
	url: string;
}

export type WidgetType = 
	| { type: "file", content: FileConfiguration }
	| { type: "url", content: UrlConfiguration };

export interface WidgetConfiguration {
	id: NanoId;
	title: string;
	widget_type: WidgetType;
	level: Level;
}

export type Modifier = 
	| { type: "scrape", content: {
	selector: string;
}}
	| { type: "refresh", content: {
}};

export interface WidgetModifier {
	id: string;
	widget_id: NanoId;
	modifier_type: Modifier;
}

