release: types
    cargo build --release

types:
    typeshare ../widget-types/src --lang=typescript --output-file=../react-ui/src/types.ts

frontend:
    cd ../react-ui
    npm run build

run: types
    RUST_LOG=info cargo run

clean:
    rm -rf widget-maker.app
    rm -rf dmg
    rm -rf icon.iconset
    rm -f widget-maker.dmg
    rm -f icon.icns

icons:
    sips -z 16 16     build_assets/app-icon2.png --out build_assets/icons/icon_16x16.png
    sips -z 32 32     build_assets/app-icon2.png --out build_assets/icons/icon_16x16@2x.png
    sips -z 32 32     build_assets/app-icon2.png --out build_assets/icons/icon_32x32.png
    sips -z 64 64     build_assets/app-icon2.png --out build_assets/icons/icon_32x32@2x.png
    sips -z 128 128   build_assets/app-icon2.png --out build_assets/icons/icon_128x128.png
    sips -z 256 256   build_assets/app-icon2.png --out build_assets/icons/icon_128x128@2x.png
    sips -z 256 256   build_assets/app-icon2.png --out build_assets/icons/icon_256x256.png
    sips -z 512 512   build_assets/app-icon2.png --out build_assets/icons/icon_256x256@2x.png
    sips -z 512 512   build_assets/app-icon2.png --out build_assets/icons/icon_512x512.png
    iconutil -c icns build_assets/WidgetMaker.iconset

app: clean release icons
    mkdir -p widget-maker.app/Contents/MacOS
    mkdir -p widget-maker.app/Contents/Resources
    cp ../target/release/widget-maker widget-maker.app/Contents/MacOS/
    cp build_assets/Info.plist widget-maker.app/Contents/
    cp icon.icns widget-maker.app/Contents/Resources/
    touch widget-maker.app

package: app
    mkdir -p dmg
    cp -R widget-maker.app dmg/
    hdiutil create -volname "Widget Maker" -srcfolder dmg -ov -format UDZO widget-maker.dmg
    rm -rf dmg



final: release
    cargo packager --release
