set dotenv-load

types:
    typeshare ../widget-types/src --lang=typescript --output-file=../react-ui/src/types.ts

frontend:
    cd ../react-ui && npm run build

# release: types frontend
release:
    cargo build --release

release-win: types frontend
    cargo build --release --target x86_64-pc-windows-gnu

convert-video:
    ffmpeg -i /Users/jarde/Downloads/interactive-widget.mov -vf scale=1280:-1 -c:v libvpx-vp9 -crf 32 -b:v 0 -c:a libopus /Users/jarde/Documents/code/web-extension-scraper/landingpage/public/interactive-widget.webm
    ffmpeg -i /Users/jarde/Downloads/example1.mov -vf scale=1280:-1 -c:v libvpx-vp9 -crf 32 -b:v 0 -c:a libopus /Users/jarde/Documents/code/web-extension-scraper/landingpage/public/example1.webm

runo:
    RUST_LOG=info cargo run

run: types frontend
    RUST_LOG=info,widget-db=info cargo run

clean:
    rm -rf hoverpane.app
    rm -rf dmg
    rm -rf icon.iconset
    rm -f hoverpane.dmg
    rm -f icon.icns

icons:
    sips -z 16 16     build_assets/icon.png --out build_assets/icons.iconset/icon_16x16.png
    sips -z 32 32     build_assets/icon.png --out build_assets/icons.iconset/icon_16x16@2x.png
    sips -z 32 32     build_assets/icon.png --out build_assets/icons.iconset/icon_32x32.png
    sips -z 64 64     build_assets/icon.png --out build_assets/icons.iconset/icon_32x32@2x.png
    sips -z 128 128   build_assets/icon.png --out build_assets/icons.iconset/icon_128x128.png
    sips -z 256 256   build_assets/icon.png --out build_assets/icons.iconset/icon_128x128@2x.png
    sips -z 256 256   build_assets/icon.png --out build_assets/icons.iconset/icon_256x256.png
    sips -z 512 512   build_assets/icon.png --out build_assets/icons.iconset/icon_256x256@2x.png
    sips -z 512 512   build_assets/icon.png --out build_assets/icons.iconset/icon_512x512.png
    iconutil -c icns build_assets/icons.iconset

icons-win:
    convert build_assets/icon.png -define icon:auto-resize=16,32,48,64,128,256 build_assets/icon.ico

final: release
    cargo packager --release --formats app

final-win: release-win
    cargo packager --release --formats nsis

